version: "3.9"
services:
  api:
    build: .
    container_name: googleplay-api
    ports:
      - "8000:8000"
    volumes:
      - ./ssp-detecta-a0181c69ec58.json:/app/ssp-detecta-a0181c69ec58.json
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=ssp-detecta-a0181c69ec58.json